adminUser:
  password: vault:jx-aps-doompickle/adminUser:password
  username: admin
dashboardAuthID: vault:jx-aps-doompickle:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:jx-aps-doompickle:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:jx-aps-doompickle/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:jx-aps-doompickle/prow:hmacToken
